version: "3.9"
   
services:
  backend:
    build: source/django_app
    command: python source/django_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  
  react:
    build: source/frontend
    ports: 
      - "3000:3000"
    command: serve -s build -l 3000
    depends_on: 
      - backend